#!/usr/bin/env node
/** Capture a generated proof locally; report custom/fallback font use, not quality. */
import {readFile, mkdir, writeFile} from 'node:fs/promises';
import {resolve, join} from 'node:path';
import {pathToFileURL} from 'node:url';

async function main() {
  const args = process.argv.slice(2);
  const input = args.shift();
  const output = args.shift();
  if (!input || !output || args.some(x => !x.startsWith('--browser-arg='))) {
    throw new Error('Usage: node capture_proof.mjs proof.html NEW_OUTPUT_DIR [--browser-arg=VALUE]');
  }
  const html = await readFile(resolve(input), 'utf8');
  if (!html.includes('id="font-evidence"') || !html.includes('window.proofReady=')) {
    throw new Error('Input must be a self-contained proof generated by build_proof.py.');
  }
  const modulePath = process.env.TYPE_REVIEW_PLAYWRIGHT;
  const {chromium} = await import(modulePath ? pathToFileURL(resolve(modulePath)).href : 'playwright');
  const browser = await chromium.launch({
    ...(process.env.TYPE_REVIEW_BROWSER ? {executablePath: process.env.TYPE_REVIEW_BROWSER} : {}),
    args: args.map(x => x.slice('--browser-arg='.length))
  });
  const root = resolve(output);
  try {
    await mkdir(root); // Fail rather than overwrite an earlier proof run.
    const reports = [];
    for (const width of [1440, 390, 320]) {
      const context = await browser.newContext({viewport: {width, height: 1000}, deviceScaleFactor: 1});
      const page = await context.newPage();
      const requestFailures = [];
      // Proofs are self-contained. Prevent loaded HTML from contacting services.
      await page.route('**/*', async route => {
        const url = route.request().url();
        if (url.startsWith('data:') || url.startsWith('about:')) await route.continue();
        else {requestFailures.push(url); await route.abort();}
      });
      await page.setContent(html, {waitUntil: 'load'});
      const runtime = await page.evaluate(() => window.proofReady);
      const client = await context.newCDPSession(page);
      await client.send('DOM.enable');
      await client.send('CSS.enable');
      const {root: doc} = await client.send('DOM.getDocument');
      const {nodeIds} = await client.send('DOM.querySelectorAll', {nodeId: doc.nodeId, selector: '.proof-sample'});
      const fonts = [];
      const hiddenSamples = [];
      const visibleSamples = new Set(await page.locator('.proof-sample').evaluateAll(elements => elements.filter(el => el.getClientRects().length).map(el => el.dataset.sample)));
      for (const nodeId of nodeIds) {
        const {node} = await client.send('DOM.describeNode', {nodeId});
        const attributes = Object.fromEntries(Array.from({length: node.attributes.length / 2}, (_, i) => [node.attributes[i * 2], node.attributes[i * 2 + 1]]));
        if (!visibleSamples.has(attributes['data-sample'])) {hiddenSamples.push(attributes['data-sample']); continue;}
        const result = await client.send('CSS.getPlatformFontsForNode', {nodeId});
        fonts.push({sample: attributes['data-sample'], fonts: result.fonts});
      }
      const full = join(root, `proof-${width}.png`);
      await page.screenshot({path: full, fullPage: true});
      const first = page.locator('.word-panel').first();
      if (await first.count()) await first.screenshot({path: join(root, `controls-${width}.png`)});
      const reading = page.locator('.word-panel').filter({has: page.locator('.reading')}).first();
      if (await reading.count()) await reading.screenshot({path: join(root, `reading-${width}.png`)});
      const hasFallback = fonts.some(x => x.fonts.some(f => f.glyphCount > 0 && !f.isCustomFont));
      const missingFontEvidence = fonts.length === 0 || fonts.some(x => !x.fonts.some(f => f.isCustomFont && f.glyphCount > 0));
      reports.push({width, engine: 'Chromium', browserVersion: browser.version(), nodePlatform: process.platform,
        runtime, fonts, hiddenSamples, hasFallback, missingFontEvidence, blockedRequests: requestFailures,
        limits: ['Screenshots must still be opened and inspected.', 'This run does not test native Office, Windows, macOS or iOS.', 'Browser names do not establish a native device platform.']});
      await context.close();
    }
    await writeFile(join(root, 'capture-report.json'), JSON.stringify(reports, null, 2) + '\n', {flag: 'wx'});
    if (reports.some(x => x.hasFallback || x.missingFontEvidence || x.blockedRequests.length)) {
      throw new Error('Evidence incomplete: fallback, missing font-use evidence or blocked external requests. See capture-report.json.');
    }
    console.log(`Captured 3 viewports in ${root}. Font use verified; visual review remains required.`);
  } finally {
    await browser.close();
  }
}

main().catch(error => {console.error(error.message); process.exitCode = 1;});
